### ISSUE TITLE
What is the relationship with LinuxNamespace?

### ISSUE THREAD

**Issue by wzlu** [tombulled/namespace#5]
Dear Sir,
Would you please tell the what the relationship with LinuxNamespace?

**Comment by tombulled** [comment]
Hi @wzlu, a namespace is way to store identifiers within their own declarative region. This helps avoid name conflicts and logically separate portions of your code-base. This library is especially useful if using Jupyter notebooks, where everything shares the same namespace.

If by LinuxNamespace you're referring to [`namespaces(7)`](https://man7.org/linux/man-pages/man7/namespaces.7.html), I'm afraid I have no experience using this and am therefore unable to comment as to its similarities/differences with this library.

The project's `README` shows example usage for this library, and I'm more than happy to help with any specific issues you encounter.

Regards, @tombulled

**Comment by wzlu** [comment]
Thank you very much.
